# Generated by Django 5.1.6 on 2025-03-03 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('unit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('age_range', models.CharField(max_length=50)),
                ('size', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure', models.FloatField()),
                ('position', models.CharField(choices=[('0', 'Parado'), ('1', 'Erecto')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('measurement_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.measurementtype')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.person')),
            ],
        ),
        migrations.CreateModel(
            name='AnthropometricTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mean', models.FloatField()),
                ('sd', models.FloatField()),
                ('percentile_5', models.FloatField()),
                ('percentile_10', models.FloatField()),
                ('percentile_25', models.FloatField()),
                ('percentile_50', models.FloatField()),
                ('percentile_75', models.FloatField()),
                ('percentile_90', models.FloatField()),
                ('percentile_95', models.FloatField()),
                ('study', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.study')),
            ],
        ),
    ]
