# Generated by Django 5.1.6 on 2025-03-11 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnthropometricTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='AnthropometricStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean', models.FloatField()),
                ('sd', models.FloatField()),
                ('percentile_5', models.FloatField(blank=True, null=True)),
                ('percentile_10', models.FloatField(blank=True, null=True)),
                ('percentile_25', models.FloatField(blank=True, null=True)),
                ('percentile_50', models.FloatField(blank=True, null=True)),
                ('percentile_75', models.FloatField(blank=True, null=True)),
                ('percentile_90', models.FloatField(blank=True, null=True)),
                ('percentile_95', models.FloatField(blank=True, null=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.anthropometrictable')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.dimension')),
            ],
            options={
                'unique_together': {('table', 'dimension')},
            },
        ),
        migrations.AddField(
            model_name='anthropometrictable',
            name='dimension',
            field=models.ManyToManyField(through='app1.AnthropometricStatistic', to='app1.dimension'),
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('position', models.CharField(choices=[('P', 'Parado'), ('S', 'Sentado')], max_length=2)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.dimension')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.person')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.study')),
            ],
        ),
        migrations.AddField(
            model_name='anthropometrictable',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.study'),
        ),
    ]
