# Generated by Django 5.1.6 on 2025-03-03 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anthropometrictable',
            name='mean',
        ),
        migrations.RemoveField(
            model_name='anthropometrictable',
            name='name',
        ),
        migrations.RemoveField(
            model_name='anthropometrictable',
            name='percentile_10',
        ),
        migrations.RemoveField(
            model_name='anthropometrictable',
            name='percentile_25',
        ),
        migrations.RemoveField(
            model_name='anthropometrictable',
            name='percentile_5',
        ),
        migrations.RemoveField(
            model_name='anthropometrictable',
            name='percentile_50',
        ),
        migrations.RemoveField(
            model_name='anthropometrictable',
            name='percentile_75',
        ),
        migrations.RemoveField(
            model_name='anthropometrictable',
            name='percentile_90',
        ),
        migrations.RemoveField(
            model_name='anthropometrictable',
            name='percentile_95',
        ),
        migrations.RemoveField(
            model_name='anthropometrictable',
            name='sd',
        ),
        migrations.AddField(
            model_name='measurement',
            name='study',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app1.study'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='measurement',
            name='position',
            field=models.BooleanField(choices=[(True, 'Parado'), (False, 'Erecto')]),
        ),
        migrations.CreateModel(
            name='AnthropometricStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean', models.FloatField()),
                ('sd', models.FloatField()),
                ('percentile_5', models.FloatField()),
                ('percentile_10', models.FloatField()),
                ('percentile_25', models.FloatField()),
                ('percentile_50', models.FloatField()),
                ('percentile_75', models.FloatField()),
                ('percentile_90', models.FloatField()),
                ('percentile_95', models.FloatField()),
                ('measurement_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.measurementtype')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.anthropometrictable')),
            ],
        ),
        migrations.AddField(
            model_name='anthropometrictable',
            name='measurement_types',
            field=models.ManyToManyField(through='app1.AnthropometricStatistic', to='app1.measurementtype'),
        ),
    ]
