# Generated by Django 5.1.6 on 2025-03-11 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='dimension',
        ),
    ]
