# Generated by Django 5.1.6 on 2025-03-04 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_anthropometrictable_mean_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anthropometricstatistic',
            name='percentile_10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anthropometricstatistic',
            name='percentile_25',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anthropometricstatistic',
            name='percentile_5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anthropometricstatistic',
            name='percentile_50',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anthropometricstatistic',
            name='percentile_75',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anthropometricstatistic',
            name='percentile_90',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anthropometricstatistic',
            name='percentile_95',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
