# Generated by Django 5.1.6 on 2025-03-11 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_measurement_dimension'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='dimension',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.dimension'),
            preserve_default=False,
        ),
    ]
