# Generated by Django 5.1.6 on 2025-03-11 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_measurement_dimension'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='measurement',
            unique_together={('study', 'person', 'dimension')},
        ),
    ]
