# Generated by Django 5.1.6 on 2025-03-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_anthropometricstatistic_percentile_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anthropometrictable',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anthropometrictable',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
