# Generated by Django 5.1.6 on 2025-03-10 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_anthropometrictable_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anthropometrictable',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.study'),
        ),
    ]
