# Generated by Django 5.1.6 on 2025-03-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_anthropometrictable_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='position',
            field=models.CharField(choices=[('P', 'Parado'), ('S', 'Sentado')], max_length=2),
        ),
    ]
