# Generated by Django 5.1.6 on 2025-03-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_studydimension'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='dimension',
            field=models.ManyToManyField(through='app1.StudyDimension', to='app1.dimension'),
        ),
    ]
