# Generated by Django 5.1.6 on 2025-03-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_study_dimension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='dimension',
        ),
        migrations.AddField(
            model_name='dimension',
            name='initial',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
