# Generated by Django 5.1.6 on 2025-03-19 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_person_country_alter_person_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimension',
            name='initial',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='app1.person'),
        ),
    ]
