# Generated by Django 5.1.6 on 2025-03-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_study_age_max_study_age_min_study_classification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('MF', 'Mixto')], default=2, max_length=2),
            preserve_default=False,
        ),
    ]
