# Generated by Django 5.1.6 on 2025-04-17 05:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_study_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anthropometrictable',
            name='dimension',
        ),
        migrations.RemoveField(
            model_name='anthropometrictable',
            name='study',
        ),
        migrations.AlterField(
            model_name='measurement',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='AnthropometricStatistic',
        ),
        migrations.DeleteModel(
            name='AnthropometricTable',
        ),
    ]
