# Generated by Django 5.1.6 on 2025-05-07 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_remove_anthropometrictable_dimension_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='supervisor',
            field=models.ForeignKey(default=1, help_text='Usuario que creó este estudio', on_delete=django.db.models.deletion.DO_NOTHING, related_name='studies', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
