# Generated by Django 5.1.6 on 2025-05-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_dimension_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimension',
            name='category',
            field=models.CharField(choices=[('0', 'Alturas'), ('1', 'Longitudes'), ('2', 'Profundidades'), ('3', 'Anchuras'), ('4', 'Diametros'), ('5', 'Circunferencias'), ('6', 'Alcances'), ('7', 'Peso')], max_length=10),
        ),
    ]
