# Generated by Django 5.1.6 on 2025-05-31 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_alter_dimension_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='end_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='start_date',
            field=models.DateField(db_index=True),
        ),
    ]
