# Generated by Django 5.1.6 on 2025-06-20 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_alter_study_end_date_alter_study_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_entries', to='app1.person')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='app1.study')),
            ],
            options={
                'verbose_name': 'Participación en estudio',
                'verbose_name_plural': 'Participaciones en estudios',
                'unique_together': {('study', 'person')},
            },
        ),
    ]
