# Generated by Django 5.1.6 on 2025-06-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_studyperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='identification',
            field=models.CharField(blank=True, help_text='Ej: cédula, DNI o pasaporte', max_length=15, null=True, verbose_name='Número de identificación'),
        ),
    ]
